#ifdef LOCKING_SUPPORT_ENABLE
#    undef LOCKING_SUPPORT_ENABLE
#endif
#ifdef LOCKING_RESYNC_ENABLE
#    undef LOCKING_RESYNC_ENABLE
#endif

#define LAYER_STATE_8BIT

#undef TAPPING_TERM
#define TAPPING_TERM 150

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define RETRO_TAPPING_PER_KEY

#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

#undef COMBO_TERM
#define COMBO_TERM 60
