#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_VARIABLE_LEN

#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT

#undef TAPPING_TERM
#define TAPPING_TERM 170

#undef DEBOUNCE
#define DEBOUNCE 20

#define QMK_KEYS_PER_SCAN 4

#undef COMBO_TERM
#define COMBO_TERM 50
